### ISSUE TITLE
Docs formatting for Matrix4

### ISSUE THREAD

**Issue by iwburns** [rustgd/cgmath#373]
I'm not exactly sure what is causing it, but the Matrix4 documentation isn't rendering properly.

It doesn't start until the `impl<$S> AsRef<[$S; ($n * $n)]> for $MatrixN<$S>` impl in `fixed_array_conversions`.  More specifically, it looks like something about the `($n * $n)`is setting it all off, because that `(` is missing from the docs (but it is in the source, obv).

Is it possible this is just a bug in cargo doc?  I say that because I just confirmed that the `as_ref` in question works properly, so there's nothing wrong with the macro itself.

**Comment by brendanzab** [comment]
Ugh - seems like it is a bug in cargo when generating docs for macro generated things... :(

**Comment by iwburns** [comment]
Well, that's unfortunate.  I did a few searches [here](https://github.com/rust-lang/cargo/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen) and didn't find any open issues on it.

Do you want to submit an issue on it, or just ignore it for now?  I wouldn't mind submitting an issue myself except for the fact that I'm not very familiar with macros yet (haven't had the need to write any at this point), so I feel like I wouldn't be a very good source of information in the ticket.

Honestly it's not the end of the world if it doesn't get fixed any time soon.  My only concern with leaving it as-is is that some of the `impl`s further down the page look like they've been deprecated or something because they are all crossed through.

**Comment by brendanzab** [comment]
Yeah - I think we should figure out a work-around. I think the issue is that I am being tricky and doing a constant numeric expression for the matrix element count. If we just passed in the element count as a constant we could get around this issue.

**Comment by nstoddard** [comment]
I don't think this is happening anymore, so unless I'm missing something, this can be closed.
