### ISSUE TITLE
Missing (?) Trait Implementations

### ISSUE THREAD

**Issue by trolleyman** [rustgd/cgmath#388]

**Comment by trolleyman** [comment]
Sorry about that, pressed enter too many times.

Anyway, to the trait implementations. Would it be logical for `Vector1`-`Vector4` to implement `One`?

Also, would it be a good idea for `Vector3` to have the function `to_homogeneous()`, like `Point3`, only with the result being `vec4(v.x, v.y, v.z, Zero::zero())`?

**Comment by brendanzab** [comment]
Not sure that `One` really makes sense for vectors... seeing as `1` is the multiplicative identity. `VectorN * VectorN -> VectorN` doesn't really make sense, and hence isn't defined for vectors, and therefore there is no sensible definition for `1`.

**Comment by brendanzab** [comment]
The homogeneous conversions are definitely gaps in the library though!
