### ISSUE TITLE
Possibility of adding project_on default method to InnerSpace?

### ISSUE THREAD

**Issue by DataAnalysisCosby** [rustgd/cgmath#416]
I think projection is a pretty common operation, so it would be useful to add to InnerSpace. 
InnerSpace makes sense because it already implements dot and magnitude2. 
If you think this is an OK change I'll submit a pull request.

**Comment by brendanzab** [comment]
What would `project_on` do?

**Comment by DataAnalysisCosby** [comment]
Compute the vector projection of self onto the argument.
https://en.m.wikipedia.org/wiki/Vector_projection
InnerSpace seems like an appropriate trait to include it in since the
Proj_b^a is defined as (a dot b)/(b dot b) * b

**Comment by brendanzab** [comment]
Sounds like a great idea! Alas, I'm going on holiday for a month, so it will be a while before I can look at merging it. But feel free to make a PR! :)
