### ISSUE TITLE
can near plane distance be zero？

### ISSUE THREAD

**Issue by piaoger** [rustgd/cgmath#467]
I got a "zero near plane distance" panic  while trying to view gltf file from Verge3d in gltf-viewer. The viewer is written in rust and using cgmath internally.  I wonder to know if near can be zero :)

- callstack

```
thread 'main' panicked at 'The near plane distance cannot be below zero, found: 0.0', /Users/piaoger/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/cgmath-0.16.1/src/projection.rs:119:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: cgmath::projection::<impl core::convert::From<cgmath::projection::PerspectiveFov<S>> for cgmath::matrix::Matrix4<S>>::from
   8: gltf_viewer::render::camera::Camera::update_projection_matrix
   9: gltf_viewer::render::camera::Camera::from_gltf
  10: gltf_viewer::render::node::Node::from_gltf
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  12: gltf_viewer::render::root::Root::from_gltf
  13: gltf_viewer::viewer::GltfViewer::new
  14: gltf_viewer::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
```

And in cgmath, I found below code lines and it seems zero near is not allowed:
```
assert!(
            persp.near > S::zero(),
            "The near plane distance cannot be below zero, found: {:?}",
            persp.near
);
```

**Comment by firestorm713** [comment]
In short, no. This is a bug in gltf-viewer's code. I'd report it there, with this issue and the backtrace.

In long, _technically,_ but it would mean that the whole scene would evaluate to a single point, so it wouldn't be *useful* to allow for it. Unity sort of lets you do it, by letting you _enter_ zero, but then under the hood, it sets it to an epsilon value (0.0001 or somesuch). This is what gltf-viewer should be doing.

**Comment by Rhuagh** [comment]
I believe we set it to something small in amethyst for this reason. I'm gonna close this bug here.
