### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by brendanzab** [rustgd/cgmath#468]
Hello all!

I'm incredibly sorry with my lack of involvement in cgmath as of late. I currently have a bunch of notifications in my Github inbox that I have been avoiding clicking on, which is never a good sign! A big problem is that I'm not currently working on any game projects myself which makes it incredibly hard to empathise with current pain-points with the library as it currently stands.

I was wondering if anyone, or a group of people would be willing to take up the reigns of cgmath, seeing as it is obvious that I can no longer invest time in the project? If not I might be able to put up a notice that redirects people to more actively developed libraries like nalgebra or euler.

cc. #419

**Comment by brendanzab** [comment]
Another option would be to continue under my user name, but to allow others to merge and publish releases. I've already given out a number of collaboratorships and cargo owners, but I might not have been clear enough about how much leeway I was going to be giving to those people. 🤔

I do know that my lack of activity has caused some downstream maintainers pain in the past. See nannou-org/nannou#131

**Comment by shmutalov** [comment]
@kvark ping )

**Comment by brendanzab** [comment]
Awesome! I'll leave this open for a bit for any other folks to pipe up about their preferences, but that seems like a good plan.

**Comment by ozkriff** [comment]
[People are beginning to ask questions](https://users.rust-lang.org/t/my-gamedever-wishlist-for-rust/2859/77))

**Comment by brendanzab** [comment]
So it seems we are ok to move it to rustgd? Who would be in charge of maintenance? @torkleyy seems to be the only publicly listed member.

I also will be around to answer questions.

**Comment by torkleyy** [comment]
I'm just the only one visible. @kvark has write access, @Xaeroxe, @Rhuagh, @omni-viral

**Comment by torkleyy** [comment]
I don't think I could be "in charge of maintenance" though since I didn't use cgmath that much. @Rhuagh certainly knows a lot about it (he wrote a physics library with it) and @kvark does, too.

**Comment by Rhuagh** [comment]
My time is severely limited nowadays though, and I don't feel comfortable with being in charge. That being said, we have no issues bringing it over to rustgd and adding more maintainers there.

**Comment by brendanzab** [comment]
@Osspial has also been making recent commits, which have been really helpful!

**Comment by omni-viral** [comment]
If the crate will be owned by [rustgd](https://github.com/rustgd) then it won't be single person resposnibility. `cgmath` is used by amethyst, so its developers (some of which are by chance rustgd members) are interested in `cgmath` to be in good condition.

**Comment by brendanzab** [comment]
Awesome! That's very good to hear! I'm also perfectly happy for things to be taken in an alternate design direction if need be, but feel free to reach out if you have any questions. I believe @kvark and @ozkriff have crate ownership rights as well.

**Comment by brendanzab** [comment]
Ah, one hiccup: I get the error "You don’t have the permission to create repositories on rustgd" when I try to transfer it. 😅

**Comment by torkleyy** [comment]
Invitation sent.

**Comment by brendanzab** [comment]
Transfer done! Feel free to remove me from the organization if you want - I don't mind either way though. I'll still stay subbed to the repo and answer questions when I have time.
