### ISSUE TITLE
dot product missing for Vector3<isize> ?

### ISSUE THREAD

**Issue by m4b** [rustgd/cgmath#470]
porting simple function from nalgebra:

```rust
let scale: isize = 2 * normal.0.dot(&self.0);
```

fails with:

```
error[E0599]: no method named `dot` found for type `cgmath::vector::Vector3<isize>` in the current scope
  --> src/vel.rs:26:41
   |
26 |         let scale: isize = 2 * normal.0.dot(&self.0);
   |                                         ^^^
   |
   = note: the method `dot` exists but the following trait bounds were not satisfied:
           `cgmath::vector::Vector3<isize> : cgmath::structure::InnerSpace`
```

Is there a reason why I can't take the dot product of isize vectors? (which is defined and mathematically sensible)

Or am I missing something and need to import something?

**Comment by kvark** [comment]
cgmath has quite a few traits responsible for different aspects of the objects, you can get most by `use cgmath::prelude::*`. Also see #419 for my complain about that :)

> note: the method `dot` exists but the following trait bounds were not satisfied:
           `cgmath::vector::Vector3<isize> : cgmath::structure::InnerSpace`

**Comment by m4b** [comment]
I really could have sworn I imported cgmath::prelude but perhaps not. I’ll try again.

And let me echo the sentiments in that issue: 
1. Importing a prelude to get the dot operation seems like overkill.
2. Having a trait for something like that seems explicitly against the design goals of the crate.
3. I popped in to find a implementation to adapt and instead found a nest of extremely complicated macros, making finding the implementation non trivial.
4. At that stage I feel like I’m in a similar place as nalgebra, which makes me doubt ever porting at all...

**Comment by kvark** [comment]
Actually, it looks like `InnerSpace` is only implemented for `BaseFloat` bound types. It would be good to make it more flexible and include integers.

**Comment by m4b** [comment]
magnitude is also missing... not sure what else? Probably going to switch back to nalgebra

**Comment by kvark** [comment]
Magnitude for integers? Doesn't make much sense, since the result is generally a non-integer. We could/should have `magnitude2` though.

**Comment by m4b** [comment]
Yes magnitude2 and the Manhattan distance spring to mind but they appear absent.
