### ISSUE TITLE
Quaternion::slerp gives different result than gl-matrix

### ISSUE THREAD

**Issue by kocsis1david** [rustgd/cgmath#498]
I'm implementing skeletal animation and there were glitches for a very short time. After some debugging, it seems that a call to `slerp` gives different results:

```rs
use cgmath::Quaternion;

fn main() {
    let a = Quaternion::<f32>::new(0.00052311074, 0.9999999, 0.00014682197, -0.000016342687);
    let b = Quaternion::<f32>::new(0.019973433, -0.99980056, -0.00015678025, 0.000013882192);

    println!("{:?}", a.slerp(b, 0.5));
}
```

This prints:

```
Quaternion { s: 1.0001583, v: Vector3 [0.009726516, -0.0004859287, -0.000120063356] }
```

I've tried the same quaternions with gl-matrix:

```
const a = quat.fromValues(0.9999999, 0.00014682197, -0.000016342687, 0.00052311074);
const b = quat.fromValues(-0.99980056, -0.00015678025, 0.000013882192, 0.019973433);

const r = quat.create();
quat.slerp(r, a, b, 0.5);
console.log(r);
```

And this prints (the scalar part is the last component here):

```
Float32Array(4) [0.9999527335166931, 0.00015180908667389303, -0.000015113232620933559, -0.009725671261548996]
```

**Comment by kvark** [comment]
Looks like the `slerp` produced a non-normalized quaternion ("s: 1.0001583"), which isn't great.

**Comment by aloucks** [comment]
You also need to check if the dot product is negative. cgmath should probably check for this but it doesn't. It would be nice to have it documented, at a minimum. 

https://stackoverflow.com/questions/2886606/flipping-issue-when-interpolating-rotations-using-quaternions/2887128#2887128

> Remember, each rotation can actually be represented by two quaternions, q and -q. But the Slerp path from q to w will be different from the path from (-q) to w: one will go the long away around, the other the short away around. It sounds like you're getting the long way when you want the short way.
> 
> Try taking the dot product of your two quaternions (i.e., the 4-D dot product), and if the dot product is negative, replace your quaterions q1 and q2 with -q1 and q2 before performing Slerp.
