### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by kvark** [rustgd/cgmath#507]
@Rhuagh @torkleyy @brendanzab 
Since I happen to be the maintainer today, can I has the proper permissions on this project? I'm not too excited about this either, since I've not been doing any math. If somebody else wants to maintain, I'll be happy :)

**Comment by brendanzab** [comment]
Set you to admin! I can empathise to the struggle of trying to maintain something out of your current area of focus though - finding other stewards is hard. 😓
